/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectolfp;

import java.awt.Desktop;
import java.io.BufferedReader;
import java.io.DataInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.URL;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author jonat
 */
public class Game extends javax.swing.JFrame {

    /**
     * Creates new form Game
     */
    public Game() {
       
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Areaconsola = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        Jbanalizar = new javax.swing.JButton();
        JBguardarcomo = new javax.swing.JButton();
        Jbabrir = new javax.swing.JButton();
        Jbacerca = new javax.swing.JButton();
        Jbsalir = new javax.swing.JButton();
        jbreporte = new javax.swing.JButton();
        Botonver = new javax.swing.JButton();
        prueba = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Areaconsola.setColumns(20);
        Areaconsola.setRows(5);
        jScrollPane1.setViewportView(Areaconsola);

        jLabel1.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        jLabel1.setText("Consola");

        Jbanalizar.setText("Analizar");
        Jbanalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbanalizarActionPerformed(evt);
            }
        });

        JBguardarcomo.setText("Guardar como");
        JBguardarcomo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBguardarcomoActionPerformed(evt);
            }
        });

        Jbabrir.setText("Abrir");
        Jbabrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbabrirActionPerformed(evt);
            }
        });

        Jbacerca.setText("Acerca de");
        Jbacerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbacercaActionPerformed(evt);
            }
        });

        Jbsalir.setText("Salir");
        Jbsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbsalirActionPerformed(evt);
            }
        });

        jbreporte.setText("Reporte de Tokens");
        jbreporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbreporteActionPerformed(evt);
            }
        });

        Botonver.setText("Ver Tablero");
        Botonver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbreporte)
                                .addGap(32, 32, 32)
                                .addComponent(Botonver)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Jbabrir, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Jbanalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JBguardarcomo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Jbacerca, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Jbsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(prueba, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(209, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Jbanalizar)
                        .addGap(18, 18, 18)
                        .addComponent(Jbabrir)
                        .addGap(18, 18, 18)
                        .addComponent(JBguardarcomo)
                        .addGap(18, 18, 18)
                        .addComponent(Jbacerca)
                        .addGap(18, 18, 18)
                        .addComponent(Jbsalir)
                        .addGap(18, 18, 18)
                        .addComponent(prueba, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbreporte)
                            .addComponent(Botonver))))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBguardarcomoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBguardarcomoActionPerformed
        
    JFileChooser seleccionar = new JFileChooser();
    File archivo;
    FileOutputStream salida;
        
        if(seleccionar.showDialog(this, "Guardar")==JFileChooser.APPROVE_OPTION){
            archivo=seleccionar.getSelectedFile();
            if(archivo.getName().endsWith("txt")){
                String Docuemnto= Areaconsola.getText();
                String mensaje = Guardar(archivo, Docuemnto);
                if(mensaje!=null){
                    JOptionPane.showMessageDialog(null, mensaje);
                }else{
                    JOptionPane.showMessageDialog(null, "Archivo no Compatible");
                }
            }else {
                JOptionPane.showMessageDialog(null, "Guardar Documento de Texto");
            }
        }
        
    }//GEN-LAST:event_JBguardarcomoActionPerformed

    private void JbacercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbacercaActionPerformed
        JOptionPane.showMessageDialog(null,"Jonatan Alejandro Azurdia Aju \n" + "201512786 \n" + "LFP");
//        String path = "C:\\Users\\jonat\\Desktop\\Rmd\\castillo.png";
//        URL url = this.getClass().getResource(path);
//        ImageIcon icon = new ImageIcon(url);
//        
//        prueba.setIcon(icon);
            
prueba.setIcon(new ImageIcon("C:\\Users\\jonat\\Desktop\\Rmd\\castillo.png"));

//String cadena = "super.jpg";
//ImageIcon imagen = new ImageIcon(cadena);
//
//prueba.setIcon(imagen);

    }//GEN-LAST:event_JbacercaActionPerformed

    private void JbsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbsalirActionPerformed
    
       int option = JOptionPane.showConfirmDialog(null, "Desea Cerrar la aplicacion?","Cerrar Aplicacion",JOptionPane.YES_NO_OPTION);
        if(JOptionPane.OK_OPTION == option){
            System.exit(0);
        }else {
            
        }
    }//GEN-LAST:event_JbsalirActionPerformed

    private void JbanalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbanalizarActionPerformed
        Analizador scanner = new Analizador(Areaconsola.getText());        
        scanner.Escaner_J();        
        scanner.Arbitro();
        
        for(int i =0; i<scanner.Lista_Errores.size();i++){ //borrar esto por si pasa algo
            if(scanner.Lista_Errores != null){
             generar();
            }
        }
        
      
    }//GEN-LAST:event_JbanalizarActionPerformed

    private void JbabrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbabrirActionPerformed
           JFileChooser selector = new JFileChooser();
            selector.showOpenDialog(selector);
            String nuevo = "";
            
            try{
               String direccion = selector.getSelectedFile().getAbsolutePath();
               FileInputStream archivo = new FileInputStream(direccion);
                DataInputStream entrada = new DataInputStream(archivo);
                
                BufferedReader lector = new BufferedReader(new InputStreamReader(entrada));
                String lineas;
                
                while((lineas = lector.readLine()) != null){
                  nuevo += lineas + "\n";
                  Areaconsola.setText(nuevo);
                }
                
                entrada.close();
                
            }catch(Exception ios){
                JOptionPane.showMessageDialog(null, "No se cargo ningun archivo");
            }
    }//GEN-LAST:event_JbabrirActionPerformed

    private void jbreporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbreporteActionPerformed
       Analizador reporte = new Analizador(Areaconsola.getText());
       reporte.GenerarReporteTokens();
       
                        try {
                        File path = new File ("C:\\Users\\jonat\\Documents\\NetBeansProjects\\ProyectoLFP\\Reportedetokens.html");
                        Desktop.getDesktop().open(path);
                        }catch (IOException ex) {
                        ex.printStackTrace();
                        }
       
    }//GEN-LAST:event_jbreporteActionPerformed

    private void BotonverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonverActionPerformed
   Tablero nuevo = new Tablero();
   nuevo.setVisible(true);
    }//GEN-LAST:event_BotonverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Areaconsola;
    private javax.swing.JButton Botonver;
    private javax.swing.JButton JBguardarcomo;
    private javax.swing.JButton Jbabrir;
    private javax.swing.JButton Jbacerca;
    private javax.swing.JButton Jbanalizar;
    private javax.swing.JButton Jbsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbreporte;
    private javax.swing.JLabel prueba;
    // End of variables declaration//GEN-END:variables

public String Guardar(File archivo, String documento){
        FileOutputStream salida;
        String mensaje=null;
        try{
            salida= new FileOutputStream(archivo);
            byte[] bytxt=documento.getBytes();
            salida.write(bytxt);
            mensaje="Archivo guardado";
        }catch(IOException e){ 
            System.out.println("Error: "+e.getMessage());
        }
        
        return mensaje;
    }
    

public void generar(){
    
     Analizador reporte = new Analizador(Areaconsola.getText());
       reporte.GenerarReporteErrores();
       
                        try {
                        File path = new File ("C:\\Users\\jonat\\Documents\\NetBeansProjects\\ProyectoLFP\\Reportedeerrores.html");
                        Desktop.getDesktop().open(path);
                        }catch (IOException ex) {
                        ex.printStackTrace();
                        }
    
}


}
